markdown: CommonMarkGhPages
commonmark:
 options: ["UNSAFE", "SMART", "FOOTNOTES"]
 extensions: ["strikethrough", "autolink", "table", "tagfilter"]
plugins:
  - jekyll-sitemap
google_analytics: G-64HQB5R4XW
description: "このサイトは筆者の学習用のメモです"